version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    entrypoint: bin/start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
