default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # username: postgres
  # host: db

development:
  <<: *default
  database: suggestion_box_development

test:
  <<: *default
  database: suggestion_box_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
